version: "3.8"

name: vue3-nginx-docker-template_prod

services:
  nginx:
    image: nginx
    restart: "no"
    container_name: "vue3-nginx-docker-template_nginx_prod"
    ports:
      - 80:80
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/conf.d
